[2024-02-07T00:00:03.745+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-postgres-dag.create_table scheduled__2024-02-06T00:00:00+00:00 [queued]>
[2024-02-07T00:00:03.766+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-postgres-dag.create_table scheduled__2024-02-06T00:00:00+00:00 [queued]>
[2024-02-07T00:00:03.771+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-07T00:00:03.814+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): create_table> on 2024-02-06 00:00:00+00:00
[2024-02-07T00:00:03.830+0000] {standard_task_runner.py:60} INFO - Started process 1816 to run task
[2024-02-07T00:00:03.855+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '***-postgres-dag', 'create_table', 'scheduled__2024-02-06T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/election_dag.py', '--cfg-path', '/tmp/tmp7urmixo_']
[2024-02-07T00:00:03.860+0000] {standard_task_runner.py:88} INFO - Job 53: Subtask create_table
[2024-02-07T00:00:03.991+0000] {task_command.py:423} INFO - Running <TaskInstance: airflow-postgres-dag.create_table scheduled__2024-02-06T00:00:00+00:00 [running]> on host 4775ae97916b
[2024-02-07T00:00:04.192+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='El_mboup' AIRFLOW_CTX_DAG_ID='***-postgres-dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-06T00:00:00+00:00'
[2024-02-07T00:00:04.196+0000] {sql.py:276} INFO - Executing: 
   CREATE TABLE IF NOT EXISTS candidatures_presidentielle (
       id SERIAL PRIMARY KEY,
       prenom VARCHAR(255),
       nom VARCHAR(255),
       parti VARCHAR(255),
       satut_validation VARCHAR(50)
   );
   
[2024-02-07T00:00:04.228+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-02-07T00:00:04.260+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-02-07T00:00:04.279+0000] {sql.py:450} INFO - Running statement: 
   CREATE TABLE IF NOT EXISTS candidatures_presidentielle (
       id SERIAL PRIMARY KEY,
       prenom VARCHAR(255),
       nom VARCHAR(255),
       parti VARCHAR(255),
       satut_validation VARCHAR(50)
   );
   , parameters: None
[2024-02-07T00:00:04.294+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/election_dag.py", line 57, in create_candidate_table
    PostgresOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 398, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 455, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(candidatures_presidentielle_id_seq, 2200) already exists.

[2024-02-07T00:00:04.330+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=***-postgres-dag, task_id=create_table, execution_date=20240206T000000, start_date=20240207T000003, end_date=20240207T000004
[2024-02-07T00:00:04.367+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 53 for task create_table (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(candidatures_presidentielle_id_seq, 2200) already exists.
; 1816)
[2024-02-07T00:00:04.409+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-07T00:00:04.508+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
